name: Kim Frameworks
ai_config:
  default_model:
    model: gpt-5-nano
    provider: openai
  providers:
    deepseek:
      models:
        - deepseek-chat
      resource_path: u/kim/qualified_deepseek
    openai:
      models:
        - gpt-5
        - gpt-5-mini
        - gpt-4o-mini
        - gpt-5-nano
      resource_path: u/kim/kimopenai
color: '#83a3fa'
git_sync:
  repositories:
    - exclude_types_override: []
      git_repo_resource_path: $res:u/kim/appealing_git_repository
      group_by_folder: false
      settings:
        exclude_path: []
        extra_include_path: []
        include_path:
          - f/**
        include_type:
          - script
          - flow
          - app
          - folder
          - resourcetype
          - resource
          - variable
          - schedule
          - user
          - trigger
          - group
          - settings
          - workspacedependencies
      use_individual_branch: false
operator_settings:
  audit_logs: true
  folders: true
  groups: true
  resources: true
  runs: true
  schedules: true
  triggers: true
  variables: true
  workers: true
